<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10" />
    <ProjectReference Include="..\ScarletSec.Application\ScarletSec.Application.csproj" />
    <ProjectReference Include="..\ScarletSec.Domain\ScarletSec.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data/Repositories/**/*.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
